In [1]:
import torch
torch.__version__

'2.6.0+cu118'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
random_tensor = torch.rand(size = (3, 4))
random_tensor

tensor([[0.5564, 0.0817, 0.2131, 0.4276],
        [0.0563, 0.6728, 0.7984, 0.8376],
        [0.6097, 0.5220, 0.1444, 0.4896]])

In [8]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [9]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [10]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [11]:
torch.arange(0, 1, 0.02)

tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
        0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
        0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
        0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
        0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
        0.9000, 0.9200, 0.9400, 0.9600, 0.9800])

In [12]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2834, 0.8082, 0.3273, 0.4380],
        [0.7233, 0.7657, 0.5638, 0.1593],
        [0.3381, 0.5198, 0.8694, 0.0353]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [14]:
a = torch.tensor([3, 4])
b = torch.tensor([3, 4])
print(a * b)
print(a @ b.T)

tensor([ 9, 16])
tensor(25)


/tmp/ipykernel_5966/532957660.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  print(a @ b.T)


In [16]:
a.min()

tensor(3)

In [17]:
a.max()

tensor(4)

In [19]:
a.sum()

tensor(7)

In [21]:
a.type(torch.float32).mean()

tensor(3.5000)

In [22]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [23]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'