In [1]:
import torch
torch.__version__

'2.6.0+cu118'

In [3]:
# Creating a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
# Creating tensors
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.item)
print(vector.shape)

tensor([7, 7])
1
<built-in method item of Tensor object at 0x73e4ff1daad0>
torch.Size([2])


In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [13]:
torch.Size([1, 2, 3])

torch.Size([1, 2, 3])

In [14]:
# Random tensors
random_tensor = torch.rand(size = (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9275, 0.3291, 0.0812, 0.7852],
         [0.4411, 0.3713, 0.4247, 0.7511],
         [0.3022, 0.3063, 0.1190, 0.7240]]),
 torch.float32)

In [15]:
# Tensors of Zeros and Ones
zeros = torch.zeros(size = (3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
ones = torch.ones(size = (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
# tensors in a range
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [18]:
# MATMUL
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [19]:
tensor * tensor

tensor([1, 4, 9])

In [20]:
tensor @ tensor

tensor(14)

In [21]:
# Other functions
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [22]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [23]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])