# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
x = torch.rand(size = (7,7))
x, x.shape

(tensor([[0.2703, 0.5352, 0.4405, 0.2604, 0.5942, 0.6483, 0.1006],
         [0.0255, 0.1044, 0.2084, 0.0297, 0.7269, 0.3741, 0.8196],
         [0.2269, 0.5862, 0.9236, 0.3349, 0.9723, 0.5686, 0.1846],
         [0.2494, 0.3451, 0.3876, 0.7169, 0.4562, 0.4021, 0.7663],
         [0.1418, 0.5678, 0.9980, 0.3312, 0.8877, 0.5352, 0.6610],
         [0.6288, 0.2253, 0.7984, 0.0662, 0.3379, 0.8980, 0.6837],
         [0.6775, 0.9585, 0.1485, 0.0856, 0.0990, 0.3472, 0.1750]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
y = torch.rand(size = (1, 7))

# Perform matrix multiplication 
z = x @ y.T
z, z.shape

(tensor([[1.5353],
         [1.6176],
         [2.0801],
         [1.7630],
         [2.4417],
         [2.3359],
         [0.9701]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(size = (7,7))
y = torch.rand(size = (1, 7))

# Matrix multiply tensors
z = x @ y.T
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

# Create two random tensors on GPU
x = torch.rand(size = (2, 3)).to(device)
y = torch.rand(size = (2, 3)).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
z = x @ y.T

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
z.max(), z.min()

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max


# Find arg min
z.argmin(), z.argmax()

(tensor(0), tensor(3))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(size = (1, 1, 1, 10))

# Remove single dimensions
x = a.squeeze()

# Print out tensors and their shapes
x, x.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))